export const PRODUCT_REQUEST="PRODUCT_REQUEST"
export const PRODUCT_SUCCESS="PRODUCT_SUCCESS"
export const PRODUCT_FALIURE="PRODUCT_FALIURE"
export const SINGUP_SUCCESS="SIGNUP_SUCCESS";

export const USER_DATA="USER_DATA"

